config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/contato' => 'static#contato'

  resources :imovels, :path => "imovel"

  resources :pesquisas, :path => "/pesquisa"
  get '/:cidade', to: 'pesquisas#index'
  get '/:cidade/:bairro', to: 'pesquisas#index'

end

app/models/imovel.rb
class Imovel < ActiveRecord::Base

  has_many :fotos, :dependent => :destroy

  belongs_to :tipo
  belongs_to :cidade
  belongs_to :bairro

  attr_accessor :novo_tipo
  attr_accessor :nova_cidade
  attr_accessor :novo_bairro

  before_save :criar_assossiations
  after_destroy :cleanup

  def criar_assossiations
    self.tipo_id = Tipo.find_or_create_by(nome: novo_tipo).id unless novo_tipo.blank?
    self.cidade_id = Cidade.find_or_create_by(nome: nova_cidade).id unless nova_cidade.blank?
    self.bairro_id = Bairro.find_or_create_by(nome: novo_bairro, cidade_id: self.cidade_id).id unless novo_bairro.blank?
  end

  def self.pesquisa(cidade, bairro, tipo, banheiros, vagas, suites, quartos="", preco_min, preco_max, venda, aluguel)
    if ( cidade || bairro || tipo || banheiros || vagas || suites || (quartos && quartos != "") || preco_min || preco_max )

      imovels = Imovel.all
      imovels = imovels.where("venda = ?", false) if !(venda == "1")
      imovels = imovels.where("aluguel = ?", false) if !(aluguel == "1")
      imovels = imovels.where("cidade_id = ?", cidade["id"]) unless cidade["id"].blank?
      imovels = imovels.where("bairro_id = ?", bairro["id"]) unless bairro["id"].blank?
      imovels = imovels.where("tipo_id = ?", tipo["id"]) unless tipo["id"].blank?
      imovels = imovels.where("quartos >= ?", quartos) if quartos.present?
      imovels = imovels.where("banheiros >= ?", banheiros) if banheiros.present?
      imovels = imovels.where("suites >= ?", suites) if suites.present?
      imovels = imovels.where("preco >= ?", preco_min) if preco_min.present?
      imovels = imovels.where("preco <= ?", preco_max) if preco_max.present?
      imovels 
    else
      Imovel.all
    end
  end
    
  private

  def cleanup
      
    if !(self.tipo_id.nil?) && Imovel.find_by(tipo_id: self.tipo_id).nil?
      Tipo.find(self.tipo_id).destroy
    end

    if !(self.cidade_id.nil?) && Imovel.find_by(cidade_id: self.cidade_id).nil?
      Cidade.find(self.cidade_id).destroy
    end

    if !(self.bairro_id.nil?) && Imovel.find_by(bairro_id: self.bairro_id).nil?
      Bairro.find(self.bairro_id).destroy
    end

  end
end

app/controllers/imovels_controller.rb
class ImovelsController < ApplicationController
  before_action :set_imovel, only: [:show, :edit, :update, :destroy]

  # GET /imovels
  # GET /imovels.json
  def index
    @imovels = Imovel.pesquisa(params[:cidade], params[:bairro], params[:tipo],params[:banheiros], params[:vagas], params[:suites], params[:quartos], params[:preco_min], params[:preco_max], params[:venda], params[:aluguel])
  end

  # GET /imovels/1
  # GET /imovels/1.json
  def show
  end

  # GET /imovels/new
  def new
    @imovel = Imovel.new
  end

  # GET /imovels/1/edit
  def edit
  end

  # POST /imovels
  # POST /imovels.json
  def create
    @imovel = Imovel.new(imovel_params)

    respond_to do |format|
      if @imovel.save

        if params[:images]
          params[:images].each { |image|
            @imovel.fotos.create(image: image)
          }
        end

        format.html { redirect_to @imovel, notice: 'Imovel was successfully created.' }
        format.json { render :show, status: :created, location: @imovel }
      else
        format.html { render :new }
        format.json { render json: @imovel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /imovels/1
  # PATCH/PUT /imovels/1.json
  def update
    respond_to do |format|
      if @imovel.update(imovel_params)
        format.html { redirect_to @imovel, notice: 'Imovel was successfully updated.' }
        format.json { render :show, status: :ok, location: @imovel }
      else
        format.html { render :edit }
        format.json { render json: @imovel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /imovels/1
  # DELETE /imovels/1.json
  def destroy
    @imovel.destroy
    respond_to do |format|
      format.html { redirect_to imovels_url, notice: 'Imovel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_imovel
      @imovel = Imovel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def imovel_params
      params.require(:imovel).permit(:tipo_id, :cidade_id, :bairro_id, :venda, :aluguel, :quartos, :banheiros, :suites, :vagas, :preco, :titulo, :descricao, :descricao_curta, :novo_tipo, :nova_cidade, :novo_bairro, :destaque)
    end
end

app/helpers/imovels_helper.rb
module ImovelsHelper
end

app/views/imovels/_form.html.erb
<%= form_for @imovel, :html => { :multipart => true }  do |f| %>
  <% if @imovel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@imovel.errors.count, "error") %> prohibited this imovel from being saved:</h2>

      <ul>
      <% @imovel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field row">
     <div class="col l5">
      <%= f.label :cidade_id %>
      <%= f.collection_select :cidade_id, Cidade.order(:nome), :id, :nome, :prompt => "Escolha a cidade" %>
    </div>
    <div class="col l7 addCamp">
      ou adiciona uma nova cidade :
      <%= f.text_field :nova_cidade%>
    </div>
  </div>

  <div class="field row">
    <div class="col l5">
      <%= f.label :bairro_id %>
      <%= f.grouped_collection_select :bairro_id, Cidade.all.order(:nome), :bairros, :nome, :id, :nome, :prompt => "Escolha o bairro" %>
    </div>
    <div class="col l7 addCamp">
    ou crie um bairro:
    <%= f.text_field :novo_bairro%>
    </div>
  </div>

  <div class="field row">
    <div class="col l5">
      <%= f.label :tipo_id %>
      <%= f.collection_select :tipo_id, Tipo.all, :id, :nome, :prompt => "Selecione o tipo de imóvel" %>
    </div>
    <div class="col l7 addCamp">
      ou crie um tipo:
      <%= f.text_field :novo_tipo %>
    </div>
  </div>

  <div class="row">
    <div class="col l2">
      <div class="field">
        <%= f.label :venda %><br>
        <%= f.check_box :venda, class: "checkbox" %>
      </div>
    </div>
    <div class="col l2">
      <div class="field">
        <%= f.label :aluguel %><br>
        <%= f.check_box :aluguel, class: "checkbox" %>
      </div>
    </div>
    <div class="col l2">
      <div class="field">
        <%= f.label :destaque %><br>
        <%= f.check_box :destaque, class: "checkbox" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col l2">
      <div class="field">
        <%= f.label :quartos %><br>
        <%= f.number_field :quartos %>
      </div>
    </div>
    <div class="col l2">
      <div class="field">
        <%= f.label :banheiros %><br>
        <%= f.number_field :banheiros %>
      </div>
    </div>
    <div class="col l2">
      <div class="field">
        <%= f.label :suites %><br>
        <%= f.number_field :suites %>
      </div>
    </div>
    <div class="col l2">
      <div class="field">
        <%= f.label :vagas %><br>
        <%= f.number_field :vagas %>
      </div>
    </div>
  </div>

  <div class="field">
    <%= f.label :preco %><br>
    <%= f.number_field :preco %>
  </div>

  <div class="row">
     <div class="field">
       <%= f.label :titulo %><br>
        <%= f.text_field :titulo %>
     </div>
   
  </div>

  <div class="row">
    <div class="field">
      <%= f.label :descricao %><br>
      <%= f.text_area :descricao, rows: "10" %>
    </div>
  </div>
  <div class="row">
    <div class="field">
      <%= f.label :descricao_curta %><br>
      <%= f.text_area :descricao_curta %>
    </div>
  </div>

  <div class="field">
    <%= f.label :fotos %>
    <%= file_field_tag "images[]", type: :file, multiple: true %>  
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/imovels/edit.html.erb
<div class="container form_imovel">
<h1>Editing imovel</h1>

<%= render 'form' %>

<%= link_to 'Show', @imovel %> |
<%= link_to 'Back', imovels_path %>
</div>

app/views/imovels/index.html.erb
<div class="container  index">
<h1>Listing imovels</h1>
<%= link_to '+', new_imovel_path, class: "btn-floating btn-large waves-effect waves-light red" %>

<% @imovels.each do |imovel| %>
<div class="card-panel row imvInd">
  <div class="col l3">

    <% if (imovel.venda && imovel.aluguel) %>
      <div class="vend">VENDA</div><div class="alug">ALUGUEL</div>

    <% else %>
      <% if imovel.venda %>
        <div class="venda">VENDA</div>
      <% elsif imovel.aluguel %>
        <div class="aluguel">ALUGUEL</div>
      <% end %>
    <% end %>

    <% unless imovel.fotos.empty? %>
      <%= image_tag(imovel.fotos.first.image.url(:thumb)) %>
    <% end %>
  </div>

  <div class="col l5">
    <h4><%= imovel.titulo %></h4><p class="mostrar"> <%= imovel.cidade.nome %> > <%= imovel.bairro.nome %> </p>
    <p class="text"><%= imovel.descricao %></p>
  </div>

  <div class="col l3">
  <ul>
    <ul class="infoList">
      <li><%= inline_svg("bed.svg", class: "icone2" ) %><%= imovel.quartos %> quartos <% unless imovel.suites == 0 || imovel.suites.nil? %>, <%= imovel.suites %> suíte<% unless imovel.suites <= 1 %>s<% end %><% end %></li>
      <li><%= inline_svg("shower.svg", class: "icone2") %><%= imovel.banheiros %> banheiros <% unless imovel.suites == 0 || imovel.suites.nil? %>, <%= imovel.suites %> d<% if imovel.suites == 1 %>a<% else %>e<% end %> suíte<% unless imovel.suites <= 1 %>s<% end %><% end %></li>
      <% unless imovel.vagas == 0 || imovel.vagas.nil? %>
        <li><%= inline_svg("sedan.svg", class: "icone2") %><%= imovel.vagas %> vagas de garagem</li>
      <% end %>
    </ul>
  </ul>
  </div>
  <div class="col l1 center">
  <ul class="crud">
<!--     <li><%= form_for imovel do |f| %><%= f.check_box :destaque, class: "checkbox" %><%= f.submit %><% end %></li>
    <li><a href="/imovel/<%= imovel.id %>">Exibir</a></li> -->
    <li><%= link_to 'Modificar', edit_imovel_path(imovel), class: "edit" %></li>
    <li><%= link_to 'Deletar', imovel, method: :delete, data: { confirm: 'Tem certeza que deseja deletar este imóvel?' }, class: "delete" %></li>
  </ul>
  </div>
</div>
<% end %>

<br>
<!--   <a class="btn-floating btn-large waves-effect waves-light red"><i class="mdi-content-add"></i></a>
 -->

</div>

<%= javascript_include_tag "readmore" %>
<script>
$('.text').readmore({
  moreLink: '<a href="#">Ver mais</a>',
  lessLink: '<a href="#">Ver menos</a>'
});
</script>

app/views/imovels/new.html.erb
<div class="container form_imovel">
<h1>Novo imovel</h1>

<%= render 'form' %>

<%= link_to 'Back', imovels_path %>
</div>

app/views/imovels/show.html.erb
<div id="arrow-le" style="display:none"><%= inline_svg("arrow-left.svg", class: "arrow-left") %></div>
<div id="arrow-rig" style="display:none"><%= inline_svg("arrow-right.svg", class: "arrow-right") %></div>


<div class="container body">
  <div class="row showRow">
    <div class="col m12 l9">
      <div class="card-panel showImovel">
      <div class="endereso">
        <a href="/<%= @imovel.cidade.nome %>"><%= @imovel.cidade.nome %> </a> > 
        <a href="/<%= @imovel.cidade.nome %>/<%= @imovel.bairro.nome %>"><%= @imovel.bairro.nome %></a>
      </div>
        <div class="slider">
          <ul class="slides">
          
            <% unless @imovel.fotos.empty? %>
              <% @imovel.fotos.each do |pic| %>
                  <li>
                    <%= image_tag pic.image.url(:medium), :class => "responsive-img" %>
                  </li>
              <% end %>
            <% end %>
          </ul>
        </div>
        
        <ul class="infoList">
          <li><%= inline_svg("bed.svg", class: "icone2" ) %><%= @imovel.quartos %> quartos <% unless @imovel.suites == 0 || @imovel.suites.nil? %>, sendo <%= @imovel.suites %> suíte<% unless @imovel.suites <= 1 %>s<% end %><% end %></li>
          <li><%= inline_svg("shower.svg", class: "icone2") %><%= @imovel.banheiros %> banheiros <% unless @imovel.suites == 0 || @imovel.suites.nil? %>, sendo <%= @imovel.suites %> d<% if @imovel.suites == 1 %>a<% else %>e<% end %> suíte<% unless @imovel.suites <= 1 %>s<% end %><% end %></li>
          <% unless @imovel.vagas == 0 || @imovel.vagas.nil? %>
            <li><%= inline_svg("sedan.svg", class: "icone2") %><%= @imovel.vagas %> vagas de garagem</li>
          <% end %>
        </ul>

        <h2><%= @imovel.titulo %></h2>
        <p><%= @imovel.descricao %></p>

      </div>
    </div>

    <div class="col m8 l3">

      <div class="retangle corPrincipal lighten-1 contatoForm">
      <h3>Contato</h3>
       <form class="centerForm">
         <input type="text", placeholder="Digite seu nome...">
         <input type="text", placeholder="Digite seu email...">
         <textarea rows="6" placeholder="Deixe sua mensagem..."></textarea>
         <div class="butao">
           <button class="btn waves-effect waves-light blue" type="submit" name="action">Enviar
              <i class="mdi-content-send right"></i>
           </button>     
         </div>
       </form>
      </div>

      <div id="floatContato" class="floatContato hide-on-med-and-down">
        <h4>Mizu Imóveis</h4>
          <ul>
            <li>contato@mizuimovels.com.br</li>
            <li><a href="tel:00000000">(00)000-000</a></li>
            <li><a href="tel:00000000">(00)000-000</a></li>
          </ul>
      </div>

    </div>

    <div class="col m4 floatContato hide-on-large-only hide-on-small-only">
        <h4>Mizu Imóvels</h4>
          <ul>
            <li>contato@mizuimovels.com.br</li>
            <li><a href="tel:00000000">(00)000-000</a></li>
            <li><a href="tel:00000000">(00)000-000</a></li>
          </ul>
    </div>

  </div>
</div>

<%= javascript_include_tag "imovels" %>