config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/contato' => 'static#contato'

  resources :imovels, :path => "imovel"

  resources :pesquisas, :path => "/pesquisa"
  get '/:cidade', to: 'pesquisas#index'
  get '/:cidade/:bairro', to: 'pesquisas#index'

end

app/views/layouts/_footer.html.erb
  <footer class="corPrincipal">
    <div class="container">
      <div class="row">
        <div class="col l4 s12">
          <h5 class="white-text">Mizu Imóveis</h5>
          <p class="grey-text text-lighten-4">Av. da Folha 869 - Kanoha, Estado do Fogo</br>Tel <a href="tel:00000000">(00)000-000</a> / <a href="tel:00000000">(00)000-000</a></br>contato@mizuimoveis.com</p>
        </div>
        <div class="col l3 s12 center">
          <h5 class="white-text">Links</h5>
          <ul  class="links">

                <li><a class="white-text" href="/pesquisa?utf8=✓&cidade=&bairro=&tipo[id]=&venda=1&quartos=&banheiros=&vagas=">Venda</a></li>
                <li><a class="white-text" href="/pesquisa?utf8=✓&cidade=&bairro=&tipo[id]=&aluguel=1&quartos=&banheiros=&vagas=">Aluguel</a></li>

                <li><a class="white-text" href="/pesquisa">Pesquisar</a></li>
                <li><a class="white-text" href="/contato">Contato</a></li>

            
          </ul>
        </div>
        <div class="col l5 s12 center">
          <h5 class="white-text">Nossas redes sociais</h5>
          <ul class="social">
            <a class="white-text" href="#!"><li><%= inline_svg("facebook.svg",  class: "social-icons") %></li></a>
            <li><a class="white-text" href="#!"><%= inline_svg("twitter.svg", class: "social-icons") %></a></li>
            <li><a class="white-text" href="#!"><%= inline_svg("whatsapp.svg", class: "social-icons") %></a></li>
            <li><a class="white-text" href="#!"><%= inline_svg("telegram.svg", class: "social-icons") %></a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
 	    &nbsp;
      </div>
    </div>
  </footer>

app/views/layouts/_header.html.erb
<nav class="corPrincipal" role="navigation">
  <div class="container">
    <div class="nav-wrapper"><a id="logo-container" href="/" class="brand-logo"><h2>Mizu Imo</h2></a>
        <ul id="nav-mobile" class="right side-nav bottom-nav-menu">
          <li class="teal lighten-1 hide-on-large-only"><a id="nav-logo" href="#">Mizu Imóveis</a></li>
          <li><a href="/">Início</a></li>
          <li><a href="/pesquisa?utf8=✓&cidade=&bairro=&tipo[id]=&venda=1&quartos=&banheiros=&vagas=">Venda</a></li>
          <li><a href="/pesquisa?utf8=✓&cidade=&bairro=&tipo[id]=&aluguel=1&quartos=&banheiros=&vagas=">Aluguel</a></li>
<!--           <li><a href="/imoveis">Todos os imóveis</a></li>
 -->          <li><a href="/contato">Contato</a></li>
        </ul><a href="#" data-activates="nav-mobile" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
    </div>
  </div>
</nav>

app/views/layouts/_index.html.erb
<% @imovels.each do |imovel| %>
<div class="card-panel row">
	<div class="col l3">
    <%= imovel.venda %><%= imovel.aluguel %>
	  <% unless imovel.fotos.empty? %>
      <%= image_tag(imovel.fotos.first.image.url(:thumb)) %>
    <% end %>
	</div>
	<div class="col l5">
    <h2><%= imovel.titulo %></h2>
    <p><%= imovel.descricao %></p>
	</div>
	<div class="col l2">
	<ul>
    <li><%= imovel.quartos %></li>
    <li><%= imovel.banheiros %></li>
    <li><%= imovel.suites %></li>
    <li><%= imovel.vagas %></li>
  </ul>
  </div>
  <div class="col l1">
  	<%= form_for imovel do |f| %><%= f.check_box :destaque, class: "checkbox" %><%= f.submit %><% end %>
    <%= link_to 'Show', imovel %>
    <%= link_to 'Edit', edit_imovel_path(imovel) %>
    <%= link_to 'Destroy', imovel, method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
</div>
<% end %>

app/views/layouts/_search.html.erb
<div class="card-panel row grey lighten-4 formuPesqui">
<%= form_tag pesquisas_path, :method => "get" do %>
  

  <div class="col s12 m6 l3">
    <label class="hide-on-small-only">Cidade:</label>
      <%= select_tag(:cidade, options_from_collection_for_select(Cidade.all, 'nome', 'nome', :selected => params[:cidade]), :include_blank => "--- Cidade ---") %>
<!--       <%= collection_select :cidade, :id, Cidade.order(:nome), :id, :nome, :include_blank => "--- Cidade ---" , :selected => @cidade_select %> -->
  </div>
  
  <div class="col s12 m6 l4">
      <label class="hide-on-small-only">Bairro:</label>
      <%= select_tag(:bairro, options_from_collection_for_select(Bairro.all, 'nome', 'nome', :selected => params[:bairro]), :include_blank => "--- Bairro ---") %>
<!--       <%= grouped_collection_select :bairro, :id, Cidade.all.order(:nome), :bairros, :nome, :id, :nome, :include_blank => "--- Bairro ---", :selected => @bairro_select %> -->
  </div>    
  
  <div class="col s12 m6 l3">
      <label class="hide-on-small-only">Tipo de imóvel:</label>
      <%= collection_select :tipo, :id, Tipo.order(:nome), :id, :nome, :include_blank => "--- Tipo ---", :selected => @tipo_select %>
  </div>
  
  <div class="col s6 m3 l1">
    <div class="checkbox">
      <label style="margin-bottom: 15px;">Venda</label>
      <%= check_box_tag :venda, "1", params.has_key?(:venda) %>
    </div>
  </div>  
  
  <div class="col s6 m3 l1">
    <div class="checkbox">
      <label style="margin-bottom: 15px;">Aluguel</label>
      <%= check_box_tag :aluguel, "1", params.has_key?(:aluguel) %>
    </div>
  </div>
  
  <% optionsQ = [["-- Quartos --", ''], ["1", 1], ["2", 2], ["3", 3], ["4", 4], ["5+", 5]]  %>
  <% optionsB = [["-- Banheiros --", ''], ["1", 1], ["2", 2], ["3", 3], ["4", 4], ["5+", 5]] %>
  <% optionsV = [["-- Vagas --", ''], ["1", 1], ["2", 2], ["3", 3], ["4", 4], ["5+", 5]] %>
  
   <div class="col s6 m4 l3">
     <label class="hide-on-small-only">Quartos:</label>
    <%= select_tag(:quartos, options_for_select(optionsQ, :selected => params[:quartos])) %>
  </div>
  <div class="col s6 m4 l3">
    <label  class="hide-on-small-only">Banheiros:</label>
    <%= select_tag(:banheiros, options_for_select(optionsB, :selected => params[:banheiros])) %>
  </div>
  
  <div class="col s12 m4 l3">
  <label  class="hide-on-small-only">Vagas de garagem:</label>
  <%= select_tag(:vagas, options_for_select(optionsV, :selected => params[:vagas])) %>
  </div>
  
  <div class="col s12 l3">
    <button class="btn waves-effect waves-light btn-large corPrincipal botaoPesquisa" type="submit" name="action">Pesquisar
      <i class="mdi-content-send right"></i>
    </button>
  </div>


<% end %>
</div>

<script>
if ($(window).width() <= 600) {
  $(".container.body").removeClass("container");
}
</script>

app/views/layouts/_thumb.html.erb
<div class="col s12 m4 l3">
  <div class="card-panel imovel">
    <%= link_to "", imovel, :class => "imovel_link" %>
    <% unless imovel.fotos.empty? %>
      <a><%= image_tag(imovel.fotos.first.image.url(:thumb), class: "") %></a>
    <% end %>
    <h4><%= imovel.titulo %></h2>
    <% unless imovel.cidade.nil? %>
      <p class="cidade-nome"><%= imovel.cidade.nome %></p>
    <% end %>
    <div class="row center">
      <div class="col s4"><%= inline_svg("sedan.svg",  class: "icons") %> <%= imovel.quartos %></div>
      <div class="col s4"><%= inline_svg("bed.svg",  class: "icons") %> <%= imovel.quartos %></div>
      <div class="col s4"><%= inline_svg("shower.svg",  class: "icons shower") %> <%= imovel.banheiros %></div>
    </div>
  </div>
</div>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mizu Imóveis</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
  <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/header" %>
	<%= yield %>
<%= render "layouts/footer" %>

</body>
</html>